name: 'yarn'
description: yarns
inputs:
  cmd:
    description: 'yarn <command>'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.cmd }}
