name: deploy
on: push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
        working-directory: ./api/app
      - name: zip
        run: zip -r lambda.zip . -q
        working-directory: ./api/app
      - id: archive-build
        uses: actions/upload-artifact@v2
        working-directory: ./api/app
        with:
          name: build-output
          path: lambda.zip
          retention-days: 1

  terraform:
    needs: [lambda]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.12
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - id: download-artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - uses: ./.github/actions/terraform
        with:
          path: terraform
