name: deploy
on: push
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
        working-directory: ./api/app
      - name: zip
        run: zip -r lambda.zip . -q -x scripts
        working-directory: ./api/app
      - run: ls -l
        working-directory: ./api/app
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - uses: ./.github/actions/terraform
        with:
          path: terraform
